name: ci
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '**'

permissions:
  # Required to checkout the code
  contents: read
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/action-setup@v6
      with:
        version: 10

    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Run check
      run: pnpm check

    - name: Run unit tests
      run: pnpm test --coverage --reporter=default --reporter=github-actions
    - name: 'Report Coverage'
      if: always() 
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        json-summary-path: coverage/coverage-summary.json

  e2e:
    needs: test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/action-setup@v6
      with:
        version: 10

    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Run Playwright tests
      env:
        HOME: /root
      run: pnpm run e2e --project=${{ matrix.browser }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.browser }}-${{ matrix.shardIndex }}
        path: playwright-report/
        retention-days: 30
